100-hours-a-week/4-bull4zo-be

src/main/java/com/moa/moa_server/config/LocalSecurityConfig.java, src/main/java/com/moa/moa_server/config/security/JwtAuthenticationFilter.java, src/main/java/com/moa/moa_server/domain/auth/service/JwtTokenService.java
- #30 
- 사용자 인증을 위한 JWT 인증 필터 구현
- `JwtAuthenticationFilter` 구현: 요청 헤더에서 토큰 추출 후 SecurityContext에 인증 정보 저장
- `JwtTokenService` 내에서 validate와 userId 추출을 하나의 메서드로 통합 (validateAndExtractUserId)  
→ 동일한 JWT 파싱 로직의 중복 제거, 한 번의 파싱으로 검증 + 정보 추출까지 수행하여 효율 및 가독성 개선
- `SecurityConfig`에서 필터 등록 및 세션 관리 정책 stateless로 설정
- 없음
=> [Feat] JWT 인증 필터 구현

src/main/java/com/moa/moa_server/config/LocalSecurityConfig.java, src/main/java/com/moa/moa_server/config/security/CustomAuthenticationEntryPoint.java, src/main/java/com/moa/moa_server/config/security/JwtAuthenticationFilter.java, src/main/java/com/moa/moa_server/domain/auth/controller/AuthController.java, src/main/java/com/moa/moa_server/domain/auth/repository/TokenRepository.java, src/main/java/com/moa/moa_server/domain/auth/service/AuthService.java, src/main/java/com/moa/moa_server/domain/auth/service/RefreshTokenService.java, src/main/java/com/moa/moa_server/domain/auth/service/impl/RefreshTokenServiceImpl.java
- #28  
- 로그아웃 기능 구현 및 인증 실패 시 응답 코드 개선 (DELETE /api/v1/auth/logout)
- 로그아웃 처리
- 인증된 사용자의 리프레시 토큰 삭제 (`TokenRepository.deleteByUserId`)
- 로그아웃 시 쿠키의 max-age를 0으로 설정하여 만료 처리
- 인증 실패 응답 개선 (403 → 401)
- 유효하지 않거나 만료된 토큰 요청 시 
- Spring Security 처리 흐름으로 인해, 401 예외를 던짐에도 403 응답을 반환하는 문제
- `CustomAuthenticationEntryPoint` 추가하여 401 응답하도록 해결
- 유효한 토큰으로 로그아웃 요청 → `200 SUCCESS`
- 이미 로그아웃된 사용자 요청 → `200 ALREADY_LOGGED_OUT`
- 토큰 없이 요청 → `401 INVALID_TOKEN` (NO_TOKEN이 맞으나, Spring Security에서 구분 불가한 문제)
- 잘못된/만료된 토큰 요청 → `401 INVALID_TOKEN`
- 탈퇴한 사용자 요청 → `401 USER_WITHDRAWN`
- 없음
=> [Feat] 로그아웃 API 구현 및 인증 실패 시 401 응답 처리

src/main/java/com/moa/moa_server/domain/auth/repository/TokenRepository.java, src/main/java/com/moa/moa_server/domain/group/entity/Group.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java, src/main/java/com/moa/moa_server/domain/user/entity/User.java, src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java, src/main/java/com/moa/moa_server/domain/vote/entity/VoteModerationLog.java, src/main/java/com/moa/moa_server/domain/vote/entity/VoteResponse.java, src/main/java/com/moa/moa_server/domain/vote/entity/VoteResult.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteModerationLogRepository.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepository.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteResponseRepository.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteResultRepository.java
- #31  
- 투표 도메인 엔티티 및 리포지토리 생성
- 투표 도메인 엔티티 및 리포지토리 생성
- `Vote`: 투표 본문 및 설정
- `VoteResponse`: 유저가 투표한 항목
- `VoteResult`: 투표 결과 집계용
- `VoteModerationLog`: AI 검열 로그
- 그룹 도메인 엔티티 및 리포지토리 생성
- `Group`: 그룹 (Vote와 연관관계 매핑)
- 없음
=> [Feat] 투표 도메인 엔티티 및 리포지토리 생성

src/main/java/com/moa/moa_server/domain/global/exception/GlobalErrorCode.java, src/main/java/com/moa/moa_server/domain/global/exception/GlobalException.java, src/main/java/com/moa/moa_server/domain/global/handler/GlobalExceptionHandler.java, src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteDetailResponse.java, src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteResponseRepository.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- #33 
- 투표 내용 조회 API 구현
- 조회 권한 분기 처리 및 커스텀 예외 적용
- 투표 내용 조회 API 구현 (`GET /api/v1/votes/{voteId}`)
- 컨트롤러 및 서비스 계층 로직 작성
- 그룹 공개 여부 및 참여자 여부에 따른 접근 제한 처리
- 커스텀 예외(`FORBIDDEN`, `VOTE_NOT_FOUND`) 적용
- 유저 인증 처리 확인    - 성공 케이스
- 공개 투표 조회 확인
- 비공개 투표 조회 (등록자나 참여자만 조회 가능)
- 등록자로 조회하는 경우 확인
- 참여자로 조회하는 경우 확인
- 실패 케이스
- 등록자가 아니면서 참여자가 아닌 경우 확인 → `FORBIDDEN`
- 없음
=> [Feat] 투표 내용 조회 API 개발

src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java, src/main/java/com/moa/moa_server/domain/vote/dto/request/VoteSubmitRequest.java, src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java, src/main/java/com/moa/moa_server/domain/vote/entity/VoteResponse.java, src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- #34 
- 투표 참여 API 구현
- 응답 유효성 검증 및 그룹 접근 권한/투표 상태 확인
- 투표 참여 API 구현 (`POST /api/v1/votes/{voteId}/submit`)
- 컨트롤러 및 서비스 계층 로직 작성
- 응답 항목 번호(0: 기권, 1: 찬성, 2: 반대) 유효성 검증
- 투표 상태가 OPEN인 경우에만 참여 가능
- 비공개 그룹일 경우 그룹 멤버 여부 확인
- 중복 투표 방지 (vote_id + user_id 유니크 조건 기반)
- 커스텀 예외 적용 (`INVALID_OPTION`, `VOTE_NOT_OPENED`, `ALREADY_VOTED`, `NOT_GROUP_MEMBER`, `VOTE_NOT_FOUND`)
- 성공 케이스
- 공개 그룹 투표 참여 
- 비공개 그룹 투표 참여    
- 실패 케이스
- 투표가 존재하지 않는 경우 → `VOTE_NOT_FOUND`
- 유효하지 않은 응답 값 → `INVALID_OPTION`
- 투표가 열려있지 않은 경우 → `VOTE_NOT_OPENED`
- 그룹 멤버가 아닌 경우 → `NOT_GROUP_MEMBER` 
- 중복 투표 시도 → `ALREADY_VOTED`
- 투표 등록자도 참여 가능한가? 
- ‘투표 등록자도 한 표 행사 가능’하다고 설정하고 개발하였음.
=> [Feat] 투표 참여 API 개발

src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteOptionResult.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteResultResponse.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteResponseRepository.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- #35
- 투표 결과 조회 API 구현
- 투표 상태 및 사용자 권한 검증
- 실시간 집계 기능 적용
- 투표 결과 조회 API 구현 (`GET /api/v1/votes/{voteId}/result`)
- 컨트롤러 및 서비스 계층 로직 작성
- 투표 상태가 OPEN, CLOSED인 경우에만 조회 가능
- 등록자이거나 참여자(응답값 1, 2)인 경우에만 조회 가능 
- 기권 응답(0)은 참여자로 간주하지 않음
- 실시간 집계 처리 
- 전체 응답 수 집계 (`totalCount`)
- 항목별 응답 수 및 비율 집계 (`count`, `ratio`)
- 커스텀 예외 적용 (`VOTE_NOT_FOUND`, `FORBIDDEN`)
- 성공 케이스
- 투표 등록자 (미참여 가능) 
- 투표 참여자 (1 또는 2로 응답한 경우)
- 실패 케이스
- 투표가 존재하지 않는 경우 → `VOTE_NOT_FOUND`
- 투표 상태가 OPEN, CLOSED가 아닌 경우 → `FORBIDDEN`
- 투표 등록자나 참여자가 아닌 경우 (그룹 멤버이더라도 조회 불가) → `FORBIDDEN`
- 기권자(0번 응답) → `FORBIDDEN`
- 없음
=> [Feat] 투표 결과 조회 API 개발

src/main/java/com/moa/moa_server/config/DevSecurityConfig.java, src/main/resources/application-dev.yaml
- #36
- dev 환경에서 Spring Security 설정 개선
- JWT 인증 및 예외 처리 필터 적용
- `DevSecurityConfig`에 다음 항목 추가
- `JwtAuthenticationFilter` 적용
- `CustomAuthenticationEntryPoint` 등록
- 세션 정책을 `STATELESS`로 설정
- 기존 `LocalSecurityConfig` 구조와 통일되도록 설정 정리
- 인증 헤더 포함 시 필터 동작 정상
- 미인증 요청 시 401 응답 및 커스텀 에러 메시지 확인
- `frontend.url` 기반 CORS 정책 정상 작동
- 별도의 브랜치(feature/47-dev-security-jwt)에서 dev 설정 테스트 후 dev 브랜치에 병합 진행
=> [Feat] Dev 환경에 Jwt 인증 및 예외 처리 필터 적용

src/main/java/com/moa/moa_server/domain/global/cursor/ClosedAtVoteIdCursor.java, src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteOptionResultWithId.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/submitted/SubmittedVoteItem.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/submitted/SubmittedVoteResponse.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepositoryCustom.java, src/main/java/com/moa/moa_server/domain/vote/repository/impl/VoteRepositoryImpl.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteResultService.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- #38
- 로그인 사용자가 참여한 투표 목록을 조회하는 API 구현
- 사용자가 참여한 투표 목록 조회 API 구현 (`GET /api/v1/votes/submit`)
- 사용자가 응답한 투표만 조회
- 커서 기반 페이지네이션 (closedAt DESC, voteId DESC) 적용
- 응답에 집계 결과 포함 (`VoteOptionResultWithId`)
- 응답 DTO 설계 및 적용 (`SubmittedVoteResponse`, `SubmittedVoteItem`
- QueryDSL 기반 조건 필터링 및 정렬 처리
- 기본 요청 (커서 없음, 그룹 없음): 200 OK, 데이터 정상 조회 (사용자가 응답한 투표만 조회)
- 커서 포함 요청: 다음 페이지 정상 조회, hasNext 여부 확인
- 그룹 필터링: 특정 그룹 투표만 필터링됨. groupId=null이면 전체 그룹에서 조회
- 예외 처리:
- 잘못된 커서 형식 → 400
- 커서에 존재하지 않는 voteId 포함 → 404
- 존재하지 않는 그룹 ID → 404
- 토큰 없음 → 401
- 없음
=> [Feat] 내가 참여한 투표 목록 조회 API 개발

src/main/java/com/moa/moa_server/domain/global/cursor/GroupNameGroupIdCursor.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepository.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepositoryCustom.java, src/main/java/com/moa/moa_server/domain/group/repository/impl/GroupMemberRepositoryImpl.java, src/main/java/com/moa/moa_server/domain/user/controller/UserController.java, src/main/java/com/moa/moa_server/domain/user/dto/response/GroupLabel.java, src/main/java/com/moa/moa_server/domain/user/dto/response/GroupLabelResponse.java, src/main/java/com/moa/moa_server/domain/user/handler/UserErrorCode.java, src/main/java/com/moa/moa_server/domain/user/service/UserService.java
- #56
- 사용자가 가입한 그룹들의 라벨을 조회하는 API 구현
- 본 API는 경량 응답을 위한 별도 API로, 그룹 선택 토글 등에서 재사용 예정
- 가입한 그룹 라벨 조회 API 구현 (`GET /api/v1/user/groups/labels`)
- 사용자가 가입한 그룹의 ID와 이름(라벨) 목록 조회
- 커서 기반 페이지네이션 (groupName ASC, groupId ASC) 적용
- 첫 페이지 요청 시, 공개 그룹(groupId1=1)을 항상 최상단에 포함
- 응답 DTO 설계 및 적용 (`GroupLabel`, `GroupLabelResponse`)
- 기본 요청 (커서 없음): 공개 그룹 포함 + 가입 그룹 정렬 확인
- 커서 포함 요청: 다음 페이지 정상 조회, hasNext 여부 확인
- 정렬 확인: 이름 기준 가나다/알파벳순
- 가입한 그룹이 하나도 없는 경우: 공개 그룹만 포함된 응답 확인
- 없음
=> [Feat] 가입한 그룹 라벨 조회 API 개발

src/main/java/com/moa/moa_server/domain/group/controller/GroupController.java, src/main/java/com/moa/moa_server/domain/group/dto/request/GroupJoinRequest.java, src/main/java/com/moa/moa_server/domain/group/dto/response/GroupJoinResponse.java, src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java, src/main/java/com/moa/moa_server/domain/group/handler/GroupException.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepository.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/group/util/GroupValidator.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- #51 
- 그룹 가입 API 구현
- 그룹 가입 API 구현 (`GET /api/v1/groups/join`)
- 초대 코드 기반 그룹 가입
- 초대 코드 유효성 검사 (`GroupValidator.validateInviteCode`)
- 가입 이력에 따른 처리
- 가입 이력 없으면 새로 생성
- 탈퇴 이력이 있으면 복구 (soft delete 복원)
- 이미 가입된 경우 예외 처리
- 공개 그룹은 가입 불가 처리  
- 성공 케이스
- 초대 코드로 신규 그룹 가입
- 소문자로 초대 코드 전송 → 정상 가입 처리
- 탈퇴한 그룹 재가입 처리 (soft delete 복구)
- 실패 케이스
- 초대 코드가 없거나 형식 오류인 경우 (null, 빈 문자열, 6자 미만, 8자 초과, 영어/숫자 이외 문자 포함)
- 초대 코드에 해당하는 그룹이 없는 경우
- 공개 그룹 가입 시도
- 이미 가입된 경우
- 없음
=> [Feat] 그룹 가입 API 개발

build.gradle, src/main/java/com/moa/moa_server/domain/group/controller/GroupController.java, src/main/java/com/moa/moa_server/domain/group/dto/request/GroupCreateRequest.java, src/main/java/com/moa/moa_server/domain/group/dto/response/GroupCreateResponse.java, src/main/java/com/moa/moa_server/domain/group/entity/Group.java, src/main/java/com/moa/moa_server/domain/group/entity/GroupMember.java, src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/group/util/GroupValidator.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/main/java/com/moa/moa_server/domain/vote/util/VoteValidator.java, src/main/resources/application.yaml
- #52 
- 새 그룹 생성 API 구현
- 새 그룹 생성 API 구현 (`POST /api/v1/groups`)
- 그룹 이름 중복 검사
- 입력값 유효성 검사 (이름, 소개, 이미지 URL)
- 초대 코드 생성 로직 추가
- 생성자(OWNER) 자동 등록
- 성공 케이스
- 새 그룹 정상 생성
- 초대 코드 자동 생성 및 포함 여부 확인
- GroupMember에 OWNER 권한으로 저장
- imageUrl이 빈 문자열일 경우 null로 저장
- 실패 케이스
- 유효성 검사 실패
- 그룹 이름: 길이 제한, 허용 문자 제한
- 그룹 소개: 길이 제한
- 이미지 URL: 지정된 업로드 도메인 형식 확인
- 그룹 이름 중복 시 실패
- 없음
=> [Feat] 새 그룹 생성 API 개발

src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/user/controller/UserController.java, src/main/java/com/moa/moa_server/domain/user/dto/request/UserUpdateRequest.java, src/main/java/com/moa/moa_server/domain/user/dto/response/UserInfoResponse.java, src/main/java/com/moa/moa_server/domain/user/dto/response/UserUpdateResponse.java, src/main/java/com/moa/moa_server/domain/user/entity/User.java, src/main/java/com/moa/moa_server/domain/user/handler/UserErrorCode.java, src/main/java/com/moa/moa_server/domain/user/repository/UserRepository.java, src/main/java/com/moa/moa_server/domain/user/service/UserService.java, src/main/java/com/moa/moa_server/domain/user/util/UserValidator.java
- #53 
- #54 
- 회원정보 조회 API 구현
- 회원정보 수정 API 구현
- 회원정보 조회 API 구현 (`GET /api/v1/user`)
- 회원정보 수정 API 구현 (`PATCH /api/v1/user`)
- 닉네임 유효성 검사
- 닉네임 중복 검사 (기존 닉네임과 같은 경우는 예외 없이 성공 처리)
- 회원정보 조회 
- 회원정보 수정
- 닉네임 정상 수정
- 기존과 동일한 닉네임 → 성공
- 닉네임 유효성 검사 → 실패 시 400
- 닉네임 중복 검사 → 실패 시 409
- 없음
=> [Feat] 회원정보 조회/수정 API 개발

src/main/java/com/moa/moa_server/config/RestTemplateConfig.java, src/main/java/com/moa/moa_server/domain/auth/handler/AuthErrorCode.java, src/main/java/com/moa/moa_server/domain/auth/repository/OAuthRepository.java, src/main/java/com/moa/moa_server/domain/auth/service/AuthService.java, src/main/java/com/moa/moa_server/domain/auth/service/strategy/KakaoOAuthLoginStrategy.java, src/main/java/com/moa/moa_server/domain/auth/service/strategy/OAuthLoginStrategy.java, src/main/java/com/moa/moa_server/domain/group/entity/Group.java, src/main/java/com/moa/moa_server/domain/group/entity/GroupMember.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupMemberRepository.java, src/main/java/com/moa/moa_server/domain/group/repository/GroupRepository.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/user/controller/UserController.java, src/main/java/com/moa/moa_server/domain/user/entity/User.java, src/main/java/com/moa/moa_server/domain/user/service/UserService.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepository.java, src/main/resources/application-dev.yaml, src/main/resources/application-local.yaml, src/main/resources/application-prod.yaml, src/main/resources/application.yaml
- #29 
- 회원 탈퇴 API 구현 및 탈퇴 시 관련 데이터 처리
- 회원 탈퇴 API 구현 (`DELETE /api/v1/user`)
- 탈퇴 시 처리되는 연관 데이터:
- Group
- 사용자가 소유자인 경우, 소유자 승계 (MANAGER → MEMBER 순)
- 승계 불가능하면 그룹 Soft Delete 처리
- GroupMember / Token / OAuth
- 해당 유저 데이터 Hard Delete
- Vote
- Soft Delete (deleted_at 설정)
- VoteResponse
- 삭제하지 않음 (집계 포함 위함)
- 카카오 소셜 연결 해제 (Admin Key 기반 unlink API 호출)
- 회원 상태 변경 → Soft Delete (user_status = WITHDRAWN, withdrawn_at 설정)
- 예외 처리
- 이미 탈퇴한 유저가 같은 액세스 토큰으로 재 요청 시 → USER_WITHDRAWN 반환
- 탈퇴하고 재가입하는 경우, 새로운 user_id로 가입됨 
- 성공 케이스
- 회원 soft delete (user_status, withdrawn_at 확인)
- 그룹 소유자 승계 or 그룹 soft delete
- GroupMember, Token, OAuth 데이터 삭제
- Vote soft delete
- 카카오 unlink API 로그 확인
- 실패 케이스
- 이미 탈퇴한 유저가 재요청 시 예외 처리 (USER_WITHDRAWN)
- 데이터 정합성
- 탈퇴 유저의 투표는 조회되지 않음
- 동일한 ID로 재가입 불가 (Unique Constraint 확인) …
=> [Feat] 회원 탈퇴 API 개발

src/main/java/com/moa/moa_server/domain/auth/controller/AuthController.java, src/main/java/com/moa/moa_server/domain/auth/handler/AuthErrorCode.java, src/main/java/com/moa/moa_server/domain/auth/service/AuthService.java, src/main/java/com/moa/moa_server/domain/auth/service/strategy/KakaoOAuthLoginStrategy.java, src/main/java/com/moa/moa_server/domain/auth/service/strategy/OAuthLoginStrategy.java, src/main/resources/application-dev.yaml
- Closes #66
- 카카오 로그인에서 redirect URI를 요청에 따라 동적으로 처리하도록 개선
- 작업 이유: 기존에는 카카오 OAuth 인증 과정에서 Dev 환경의 redirect_uri가 프론트 배포 주소로 고정되어 있어, 로컬 환경에서 Dev 서버로의 로그인 테스트가 불가능했습니다. 이를 해결하기 위해 요청 헤더로 redirect URI를 받아 처리하도록 개선하였습니다.
- 카카오 로그인에서 redirect URI를 요청에 따라 동적으로 처리하도록 개선
- 프론트에서 전달한 X-Redirect-Uri 헤더를 통해 redirect URI를 받도록 변경
- Kakao 토큰 요청 시 redirect_uri를 고정값이 아닌 동적 값으로 설정
- 허용된 redirect URI 목록을 서버에서 검증하여 보안 강화
- 허용되지 않은 URI 요청 시 AuthException 발생 및 에러 로그 출력
- 허용되지 않은 URI 요청 시 AuthException 발생 및 에러 로그 출력
- 없음
=> [Feat] 카카오 로그인 시 동적 redirect URI 허용 및 검증 추가

src/main/java/com/moa/moa_server/domain/ai/controller/AiController.java, src/main/java/com/moa/moa_server/domain/vote/controller/VoteModerationController.java, src/main/java/com/moa/moa_server/domain/vote/dto/moderation/VoteModerationCallbackRequest.java, src/main/java/com/moa/moa_server/domain/vote/dto/moderation/VoteModerationCallbackResponse.java, src/main/java/com/moa/moa_server/domain/vote/dto/moderation/VoteModerationRequest.java, src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java, src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteModerationService.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/main/resources/application-local.yaml
- Closes #68 
AI 기반 콘텐츠 검열 기능을 추가하여, 사용자가 생성한 투표 내용에 대해 부적절한 내용을 사전에 필터링할 수 있도록 구현하였습니다.
- 투표 등록 시
- AI 서버로 검열 요청 전송
- 투표 상태를 PENDING으로 설정하고, 작성자 외에는 미공개 처리
- AI 서버 콜백 시
- 검열 결과를 저장하고, 투표 상태를 OPEN 또는 REJECTED로 변경
- 투표 등록 시 검열 요청 API 호출 및 PENDING 상태 설정
- AI 서버 콜백 API 구현 및 상태 업데이트 처리
- 검열 결과 저장 로직 추가
- AI 서버 요청 결과 로그 출력
- AI 서버로 정상 요청
- 투표 상태 저장 확인
- 
- []  DB 연동 동작 확인 (엔티티 저장, 삭제, 갱신 등)
- 테스트
- 투표 등록 시, AI 서버로 검열 요청 및 투표 등록 확인 완료.
- Dev 브랜치 머지 후, AI 서버 콜백 동작 테스트 예정.
- 구현
- 현재는 단순 콜백 구조이나, 비동기 큐 기반 확장 가능성 고려
=> [Feat] AI 기반 투표 내용 검열 기능 추가

src/main/java/com/moa/moa_server/domain/feedback/controller/FeedbackController.java, src/main/java/com/moa/moa_server/domain/feedback/dto/request/FeedbackCreateRequest.java, src/main/java/com/moa/moa_server/domain/feedback/entity/Feedback.java, src/main/java/com/moa/moa_server/domain/feedback/handler/FeedbackErrorCode.java, src/main/java/com/moa/moa_server/domain/feedback/handler/FeedbackException.java, src/main/java/com/moa/moa_server/domain/feedback/repository/FeedbackRepository.java, src/main/java/com/moa/moa_server/domain/feedback/service/FeedbackService.java, src/main/java/com/moa/moa_server/domain/feedback/util/FeedbackValidator.java
- Closes #77
- 사용자 피드백 등록 API 개발
- 사용자 피드백 등록 API 구현 (`POST /api/v1/user-feedback`)
- 피드백 내용 유효성 검사(빈 값, 최소/최대 길이 제한) 포함
- 피드백은 로그인된 사용자와 연동되어 저장됨
- 성공 케이스
- 피드백 정상 등록
- 실패 케이스
- 빈 문자열 또는 길이 조건 미충족 시 등록 실패
- 없음
=> [Feat] 사용자 피드백 등록 API 개발

src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/main/java/com/moa/moa_server/domain/vote/util/VoteValidator.java
- Closes #79 
- 투표 종료 시각(ClosedAt)을 KST에서 UTC로 변환하여 저장하도록 수정
- 로컬 환경에서는 검열 로직 생략 및 VoteStatus를 기본값 OPEN으로 설정
- VoteService#createVote 내 closedAt 값을 Asia/Seoul → UTC로 변환
- VoteValidator.validateClosedAt()도 UTC 기준으로 시간 검증
- 로컬 환경(spring.profiles.active=local)에서는
- 검열 요청 로직 제외
- 투표 상태를 OPEN으로 저장
- 기존 데이터베이스에 등록된 투표에 대해 closed_at - 9시간 적용
- 성공 케이스
- 정상 등록 및 검열 생략 여부 확인 (로컬/운영 구분)
- 없음
=> [Fix] 투표 종료 시각 UTC 저장 및 로컬 환경 처리 개선

src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/MyVoteItem.java
- Closes #81 
- 내가 만든 투표 목록 응답에서 voteStatus 필드를 DB의 상태값이 아닌 종료 시각(closedAt)과 현재 시각을 비교하여 동적으로 계산하도록 변경
- MyVoteItem.from(...) 내부 로직 수정
- vote.getVoteStatus().name() 대신 vote.getClosedAt().isAfter(LocalDateTime.now()) 기준으로 상태("OPEN" / "CLOSED") 결정
- 실제 종료된 투표가 OPEN으로 표시되는 문제 해결
- 내가 만든 투표 목록 조회 시 종료된 투표가 CLOSED로 정상 반환됨
- 백그라운드 스케줄러 도입 이후에도 정확성을 위해 status 대신 지금 방식 그대로 closedAt을 사용할 것 같음
=> [Fix] 투표 상태 응답을 종료 시각 기반으로 계산하도록 수정

src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/MyVoteItem.java
- 후속 작업: #81
- #81 병합 이후 상태 판단 로직에 REJECTED, PENDING 예외 처리가 누락되어 추가 반영
- 투표 상태 판단 시 REJECTED, PENDING은 voteStatus 값을 그대로 사용
- 수동 테스트 완료: 상태별 출력 정상 확인
=> [Fix] #81 병합 후 REJECTED, PENDING 상태 반영 누락 수정

src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- 재수정: 기존 PR(#79)에서 UTC 변환 후 해당 값을 사용하지 않고 원본 KST 값을 저장하던 문제 수정
- `VoteService#createVote` 메서드 내 `closedAt` 필드 저장 시 `utcTime`을 사용하도록 수정
- 기존에는 변환한 `utcTime`을 검증에만 사용하고, 저장에는 `request.closedAt()`을 그대로 사용했음
- 저장 로직에 `utcTime`이 반영되도록 수정
- [] FE에서 보낸 KST 시간 → 서버에서 UTC로 저장되는지 확인 예정
- 기존 PR 병합 이후 발견된 이슈로, 후속 조치 PR입니다
- Dev 반영 후, 실제 프론트엔드 요청이 잘 저장되는지 확인 필요
=> [Fix] Vote 종료 시각 UTC 저장 누락 수정

.github/scripts/install-hooks.sh, .github/scripts/pre-push-build.sh
develop 브랜치의 push가 허용됨에 따라 push 하기 전 dev 프로필을 사용해 build test를 진행하는 스크립트 작성
- `.github/scripts/` 추가
- 대상 브랜치: `develop`
- pre-push-build.sh: develop 브랜치에 한해 push 시 build 성공 여부 체크, 빌드 에러 발생 시 push 막힘
- install-hooks: pre-push-build 스크립트를 pre-push 트리거 설정하기 위한 최초 설정 명령어 모음
- 사소한 빌드 에러로 CI/CD 워크플로우가 실패하는 것을 막기 위해 도입
- 빌드 에러 유무를 사전에 명확히 하여 협업 효율을 높이고자 함
- 로컬에서 현재 dev 프로필을 사용해 build가 가능한지 확인 바람
- 최초 1회 `sh .github/scripts/install-hooks.sh` 명령어를 통해 hook 설치 필수
=> cicd: pre-push 트리거 build test script 작성

build.gradle, src/main/java/com/moa/moa_server/domain/global/util/XssUtil.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/main/resources/lucy-xss-superset.xml
- Closes #95
- lucy-xss-filter 기반 XSS 필터링 적용
- 사용자 입력이 저장되는 주요 필드에 XSS 필터 적용
- 적용 대상: 투표 본문(Vote.content), 그룹 소개(Group.description)
- 비적용 대상: 닉네임, 그룹 이름 등 글자 수 제한(12자)으로 인해 XSS 위험이 낮은 필드
- XssUtil 유틸리티 클래스 구현
- lucy-xss.xml 설정 기반으로 필터 초기화
- 요청 시점에서 수동 필터링 수행
- 없음
=> feat: lucy-xss-filter 기반 XSS 필터링 적용

build.gradle, config/checkstyle/checkstyle.xml, config/checkstyle/suppressions.xml
- Closes #118
- QueryDSL Q클래스는 컴파일 시 자동 생성되는 코드로, 스타일 규칙 위반이 잦고 수동 수정이 불가능합니다.
- CI 단계에서는 해당 클래스가 생성되지 않아 문제가 없지만,
CD 파이프라인에서는 ./gradlew build 과정에서 Q클래스가 생성되고, 이후 checkstyleMain이 실행되면서 스타일 위반이 발생해 배포가 중단되는 문제가 있었습니다.
- QueryDSL Q클래스가 checkstyle 검사에 포함되지 않도록 예외 처리
- `build/generated/querydsl` 디렉토리 내 파일을 checkstyle 검사에서 제외
- `suppressions.xml`에 해당 경로 추가 (`files=".*[\\/]build[\\/]generated[\\/]querydsl[\\/].*"`)
- 자동 생성된 소스는 checkstyle 대상에서 제외하는 것이 일반적
=> chore: checkstyle 검사에서 QueryDSL Q클래스 제외

db/README.md, db/testdata/init_users.sql, db/testdata/init_vote_responses.sql, db/testdata/init_votes.sql, db/testdata/truncate_all.sql, src/main/java/com/moa/moa_server/config/security/SecurityConstants.java, src/main/java/com/moa/moa_server/domain/test/controller/TestLoginController.java
- Closes #126
- 테스트 시나리오 구성을 위한 더미 데이터 삽입 SQL 스크립트 추가
- 로컬 개발 및 성능 테스트 편의를 위한 테스트용 로그인 API 구현
- `scripts/db/testdata/` 디렉토리 내 SQL 파일 작성
- `init_users.sql`: 테스트 유저 200명 생성
- `init_votes.sql`: 투표 100개 생성
- `init_vote_responses.sql`: 각 투표에 대해 사용자 200명이 랜덤 응답 생성 (총 응답 데이터 수 20,000개)
- `truncate_all.sql`: 데이터 초기화를 위한 테이블 비우기 스크립트
- `README.md` 작성: 스크립트 실행 순서, 주의사항 정리
- 자동 실행되지 않도록 수동 실행 방식 유지 (`AUTO_INCREMENT` 포함)
- 사용자 ID를 입력하면 JWT 토큰을 반환하는 테스트 전용 로그인 API 추가
- `local` 프로파일에서만 동작하도록 설정 (운영 환경 노출 방지)
- ### **테스트 및 백업 목적을 위해 해당 브랜치는 삭제하지 않음 ‼️**
=> feat: 테스트용 로그인 API 및 더미 데이터 삽입 SQL 스크립트 추가

db/README.md, db/testdata/init_vote_responses.sql, db/testdata/init_vote_results.sql, db/testdata/truncate_all.sql, src/main/java/com/moa/moa_server/config/security/LocalSecurityConfig.java, src/main/java/com/moa/moa_server/config/security/SecurityConstants.java, src/main/java/com/moa/moa_server/domain/global/handler/GlobalExceptionHandler.java, src/main/java/com/moa/moa_server/domain/test/controller/TestLoginController.java, src/main/java/com/moa/moa_server/domain/vote/controller/VoteControllerV2.java, src/main/java/com/moa/moa_server/domain/vote/handler/VoteErrorCode.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteResultRepository.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteServiceV2.java, src/main/resources/application-local.yaml
- Closes #128
- Redis 도입 전, 기존 실시간 집계 방식과의 성능 비교를 위한  
**집계 테이블 기반 투표 API(V2)** 구현
- `POST /api/v2/votes/{voteId}/submit`
- `vote_response` 저장 후, `vote_result` 테이블의 해당 옵션 count를 `+1` 증가
- `count = count + 1` 형태의 **DB 원자 연산 쿼리**를 사용하여,  
**동시성 환경에서도 정확한 집계가 이루어지도록 구현**
- `GET /api/v2/votes/submit`
- 기존 방식은 실시간 COUNT 쿼리를 통해 집계 정보를 계산
- V2에서는 `vote_result` 테이블의 count 및 ratio 값을 조회하여 집계 결과 반환
- 투표 등록 시 `vote_result` 초기화 쿼리 추가 (옵션 1, 2 기준으로 row 생성)
- Redis 기반 집계 방식(V3) 구현을 위한 기준선 확보 완료
- 실시간 집계 vs 집계 테이블 방식 간 성능 차이 측정 가능
- ###  **테스트 및 비교 실험 목적의 브랜치이므로 삭제하지 않음‼️**
=> feat: 집계 테이블 기반 투표 API(V2) 및 목록 조회 API 구현

.github/workflows/cicd-docker.yml, Dockerfile, Dockerfile.dev
* 클라우드 # 116
* 기존 CI/CD 버전 트리거 삭제 및 자동 버저닝 기능 추가
1. Dockerfile 수정
* 버전에 맞게 생성되는 .jar 파일을 사용하기 위해 기존 버전 하드코딩 대신 와일드카드(*) 사용하도록 변경
2. CI/CD 트리거 변경
* v로 시작하는 버전 태그 트리거 삭제, main 브랜치 트리거로 변경
=> cicd: main 브랜치 버전 자동 태그

build.gradle, src/main/java/com/moa/moa_server/config/aws/AwsS3Config.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/group/util/GroupValidator.java, src/main/java/com/moa/moa_server/domain/image/controller/ImageController.java, src/main/java/com/moa/moa_server/domain/image/dto/PresignedUrlRequest.java, src/main/java/com/moa/moa_server/domain/image/dto/PresignedUrlResponse.java, src/main/java/com/moa/moa_server/domain/image/handler/ImageErrorCode.java, src/main/java/com/moa/moa_server/domain/image/handler/ImageException.java, src/main/java/com/moa/moa_server/domain/image/service/ImageService.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/main/java/com/moa/moa_server/domain/vote/util/VoteValidator.java, src/main/resources/application-dev.yaml, src/main/resources/application-local.yaml, src/main/resources/application-prod.yaml, src/test/java/com/moa/moa_server/unit/image/service/ImageServiceTest.java
- Closes #103 
- S3 Presigned URL 기반 이미지 업로드, 투표/그룹 이미지 이동 및 삭제 등 이미지 파일 처리 기능 일괄 추가
1. **S3 Presigned URL 발급 API 구현**
* `POST /image/presigned-url` API 추가: 프론트엔드에서 presigned URL 발급받아 클라이언트에서 직접 S3에 이미지 업로드 가능하도록 구현
* 업로드 경로는 기본적으로 `temp/` 디렉토리 하위에 파일 저장
2. **투표/그룹 생성 시 이미지 이동 처리**
* 투표/그룹 생성 시, S3의 `temp/` 경로에 업로드된 이미지를 `vote/`, `group/` 디렉토리로 이동하도록 기능 구현
* 이동 후 실제 경로 기반으로 이미지 URL DB에 저장
3. **이미지 URL 유효성 검사 기능 도입**
* 이미지 URL이 해당 프로젝트 S3 버킷 경로인지 검증하는 로직 추가 (`ImageService.validateImageUrl`)
* 이미지 업로드, 투표/그룹 생성 등 모든 경로에서 보안성 강화
4. **S3 파일 삭제 기능 추가**
* 투표/그룹 등 하드 딜리트 시 S3 이미지 파일도 함께 삭제할 수 있도록 deleteImage 메서드 구현
5.  **S3 temp 폴더 자동 만료 정책 적용**
* S3 버킷 Lifecycle Rule을 활용하여 temp 디렉토리 내 파일은 일정 기간(1일) 경과 시 자동 삭제 처리
* Github Actions 환경 변수에 dev 프로필용 S3 버킷 환경 변수 추가 완료
prod 환경은 S3 버킷 생성 후, 관련 환경 변수 추후 …
=> feat: S3 Presigned URL 기반 이미지 업로드 및 이동/정리 기능 추가

.github/workflows/cicd-docker.yml
* S3를 사용한 이미지 업로드 기능 추가에 따른 시크릿 주입 과정 추가
1. 시크릿 주입 과정 추가
* AWS_ACCESS_KEY, AWS_REGION, AWS_SECRET_KEY, S3_BUCKET_NAME 주입 과정 추가
=> cicd: 이미지 업로드 기능 관련 시크릿 주입

.github/workflows/cicd-docker.yml, Dockerfile.dev
- 클라우드 # 124
* Elastic APM 추가를 위한 Dockerfile 수정 및 환경변수 주입
1. Dockerfile 수정
* Elastic APM 이미지 복사 과정 추가 및 CMD 실행 시 Agent 실행 과정 추가
2. 환경 변수 주입
* ELASTIC_APM_SERVER_URL, ELASTIC_APM_SERVICE_NAME, ELASTIC_APM_ENVIRONMENT 환경 변수 추가
=> cicd: 모니터링을 위한 Dockerfile.dev 수정 및 환경 변수 주입

src/main/java/com/moa/moa_server/domain/vote/service/vote_result/VoteResultResolver.java
- Closes #168 
- REJECTED/PENDING 투표 결과 조회 시 빈 리스트 반환하도록 방어 로직 추가
- Redis 집계 캐시를 도입하면서, 조회 시점에 종료시각이 지났고 DB에 vote_result 테이블 데이터가 없으면 결과를 생성하고 vote_status를 CLOSED로 변경하도록 구현함
- 여기서 REJECTED/PENDING 투표는 처리되지 않아야하는데, 방어 로직이 없어서 **실제 데이터베이스**에 있는 **REJECTED/PENDING 데이터의 vote_status 값이 모두 CLOSED로 수정되는** 문제 발생
- `VoteResultResolver.getOrComputeResults()`에
- 투표 상태가 REJECTED(반려) 또는 PENDING(미승인)인 경우, 즉시 빈 리스트(List.of()) 반환
- 해당 투표는 집계/조회/상태 변경 로직을 아예 타지 않도록 처리
* 머지 후, Dev 환경 데이터베이스에서 기존 REJECTED/PENDING 투표가 CLOSED로 잘못 변경된 데이터 복구 필요 (Local에서 복구 테스트 완료)
아래 쿼리 차례로 실행
1. REJECTED 복구
- moderation_log에 REJECTED 기록이 있는 vote만 vote 테이블에서 vote_status를 REJECTED로 되돌림
```sql
UPDATE vote v
JOIN (
SELECT DISTINCT vote_id
FROM vote_moderation_log
WHERE review_result = 'REJECTED'
) vm
ON v.id = vm.vote_id
SET …
```
=> fix: REJECTED/PENDING 투표는 결과 조회 시 빈 리스트 반환하도록 방어 로직 추가

.github/workflows/cicd-docker.yml
* Prod 서버 S3를 사용한 이미지 업로드 기능 추가, Redis 도입에 따른 시크릿 주입 과정 추가
1. 시크릿 주입 과정 추가
* AWS_ACCESS_KEY, AWS_REGION, AWS_SECRET_KEY, S3_BUCKET_NAME, REDIS_URL, REDIS_PORT, REDIS_PASSWORD 주입 과정 추가
=> cicd: AWS 버킷, Redis secret 주입 과정 추가

src/main/java/com/moa/moa_server/domain/image/service/ImageService.java
- Closes #171 
- S3 파일명 정책 및 jpg Content-Type 처리 개선
- S3 업로드 시 파일명에 **uuid + 원본 파일명** 포함되도록 key 생성 방식 개선  
→ ex) `temp/{uuid}_{filename}.ext`
- jpg 확장자 파일의 Content-Type을 `image/jpeg`로 올바르게 지정  
* 없음
=> feat: S3 파일명 정책 및 jpg Content-Type 처리 개선

src/main/java/com/moa/moa_server/domain/image/service/ImageService.java
* #176 
* S3 한글/특수문자 파일명 업로드 및 이동 문제 해결
* presigend-url 발급 API에서 DB 저장 위한 fileURl을 프론트로 발급 시 fileUrl에 대해 URL 인코딩 적용
* 프론트에서는 디코딩해서 기존 파일명 그대로 노출 필요
* prod 스키마/정책에는 영향 없음
=> fix: S3 파일명 한글/특수문자 대응 - fileUrl 인코딩 처리

src/main/java/com/moa/moa_server/domain/group/dto/request/GroupCreateRequest.java, src/main/java/com/moa/moa_server/domain/group/dto/response/GroupCreateResponse.java, src/main/java/com/moa/moa_server/domain/group/entity/Group.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/image/service/ImageService.java, src/main/java/com/moa/moa_server/domain/user/dto/response/GroupDetail.java, src/main/java/com/moa/moa_server/domain/vote/dto/request/VoteCreateRequest.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteDetailResponse.java, src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/main/java/com/moa/moa_server/support/GroupTestFactory.java
- Closes #176 
- vote, group 테이블에 image_name 컬럼 추가 및 파일명 저장 로직 구현
- 필요성
- 투표 내용 수정 시 사용자에게 기존 이미지 파일명을 보여주기 위해 파일명을 저장하고 있어야 할 필요성이 생김
- 기존에는 image_url 컬럼만 있었으며, S3 객체명을 UUID로만 저장하고 있어서 파일명을 따로 저장하고 있지 않았음
- **S3 객체명에 파일명을 포함하는 방식 도입 및 롤백**
- S3 객체명에 `{UUID}_{파일명}` 이렇게 파일명을 추가하여, image_url에 파일명을 저장하고 FE에서는 이를 파싱하여 사용자에게 보여주도록 구현
- 한글 파일명을 허용함에 따라 FE에서 파일명을 **두 번 디코딩**해야 하는 문제 발생
- S3에서 객체가 저장될 때 객체명 인코딩 발생(1회), 고아 이미지 문제 해결 전략으로 투표 등록 시 이미지를 `temp/`에서 `vote/`로 이동할 때 객체명 인코딩이 한 번 더 발생(2회)
- 위와 같이 모아의 이미지 관리 전략과 S3 기본 동작에 따라 필연적으로 **인코딩이 두 번 발생**
- FE에서 두 번 디코딩해야 한다는 점, 파일 이름을 URL에 포함하면 URL이 길어지는 점 때문에 이 방식이 실용적이지 않다고 판단
- 결론: **S3 객체명은 UUID으로만 구성하고, 테이블에 image_name 컬럼을 추가하여 이미지 이름을 별도로 저장하는 방식 채택**
- 기대 효과
- 한글/특수문자 파일명 안전하게 처리
- S3 객체명을 깔끔하게 유지
- 프론트엔드에서 사용자에게 원본 파일명을 쉽게 노출
- vote, group …
=> feat: vote, group 테이블에 image_name 컬럼 추가 및 파일명 저장 로직 구현

build.gradle, src/main/java/com/moa/moa_server/domain/comment/controller/CommentController.java, src/main/java/com/moa/moa_server/domain/comment/dto/request/CommentCreateRequest.java, src/main/java/com/moa/moa_server/domain/comment/dto/response/CommentCreateResponse.java, src/main/java/com/moa/moa_server/domain/comment/entity/Comment.java, src/main/java/com/moa/moa_server/domain/comment/handler/CommentErrorCode.java, src/main/java/com/moa/moa_server/domain/comment/handler/CommentException.java, src/main/java/com/moa/moa_server/domain/comment/repository/CommentRepository.java, src/main/java/com/moa/moa_server/domain/comment/service/CommentService.java, src/main/java/com/moa/moa_server/domain/global/handler/GlobalExceptionHandler.java, src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteResponseRepository.java, src/test/java/com/moa/moa_server/integration/comment/CommentCreateIntegrationTest.java, src/test/java/com/moa/moa_server/util/TestFixture.java, src/test/java/com/moa/moa_server/util/TestUtil.java
* Closes #189
* 댓글 작성 API 구현
* 댓글 도메인 패키지 및 기본 구조 생성
* 댓글 엔티티, 에러 핸들러, 에러코드, 레포지토리 등 
* 댓글 작성 API 구현 (`POST /api/v1/votes/{voteId}/comments`)
* 본문, 익명 여부 입력값 검증
* 투표 등록자 또는 유효 응답(1, 2) 투표 참여자만 댓글 작성 가능하도록 권한 체크
* 익명 댓글 작성 시 투표별 익명 번호 할당 및 재사용
* 댓글 내용 XSS 필터링 적용
* 댓글 작성 성공 시 상세 정보 반환
* 댓글 작성 관련 통합 테스트 작성
* 권한/유효성/익명번호/실명/실패 케이스 포함
* 통합 테스트, Postman 테스트, DB 수동 검증 완료
* Prod 데이터베이스에 테이블 수동 생성 완료
=> feat: 댓글 작성 API 구현

build.gradle, src/main/java/com/moa/moa_server/domain/comment/controller/CommentController.java, src/main/java/com/moa/moa_server/domain/comment/dto/response/CommentItem.java, src/main/java/com/moa/moa_server/domain/comment/dto/response/CommentListResponse.java, src/main/java/com/moa/moa_server/domain/comment/handler/CommentErrorCode.java, src/main/java/com/moa/moa_server/domain/comment/repository/CommentRepository.java, src/main/java/com/moa/moa_server/domain/comment/repository/CommentRepositoryCustom.java, src/main/java/com/moa/moa_server/domain/comment/repository/impl/CommentRepositoryImpl.java, src/main/java/com/moa/moa_server/domain/comment/service/CommentService.java, src/main/java/com/moa/moa_server/domain/comment/util/CommentNicknameUtil.java, src/main/java/com/moa/moa_server/domain/global/cursor/CreatedAtCommentIdCursor.java, src/test/java/com/moa/moa_server/integration/comment/CommentListIntegrationTest.java, src/test/java/com/moa/moa_server/util/TestFixture.java
* Closes #191
* 댓글 목록 조회 API 구현
* 댓글 목록 조회 API 구현 (`GET /api/v1/votes/{voteId}/comments`)
* 커서 기반 페이지네이션 (createdAt, commentId 조합)
* 투표 등록자 또는 유효 응답(1, 2) 투표 참여자만 조회 가능하도록 권한 체크
* 숨김/삭제 댓글 처리(숨김 사유 메시지 등)
* 댓글 작성자 여부(isMine), 익명 닉네임, 신고 여부 등 상세 정보 포함
* 통합 테스트 코드 작성 (권한/커서/예외/숨김/작성자 등)
* 통합 테스트, Postman 테스트 완료
* 없음
=> feat: 댓글 목록 조회 API 구현

src/main/java/com/moa/moa_server/domain/auth/dto/model/KakaoUserInfo.java, src/main/java/com/moa/moa_server/domain/auth/entity/OAuth.java, src/main/java/com/moa/moa_server/domain/auth/repository/OAuthRepository.java, src/main/java/com/moa/moa_server/domain/auth/service/strategy/KakaoOAuthLoginStrategy.java, src/main/java/com/moa/moa_server/domain/user/entity/User.java
- Closes #200
- 카카오 로그인 연동 시 카카오 계정의 닉네임과 이메일을 함께 저장하도록 개선
- 카카오 로그인 시, 카카오에서 제공하는 닉네임과 이메일 정보를 받아와 DB에 저장
- 신규 회원가입 시 닉네임/이메일 모두 저장
- 기존 회원인 경우 닉네임/이메일 정보가 누락되어 있으면 보완
- `OAuth` 테이블 `oauth_nickname` 컬럼 추가
* Prod 데이터베이스에 `oauth_nickname` 필드 추가 필요
=> feat: 카카오 로그인 시 닉네임, 이메일 저장 추가

src/main/java/com/moa/moa_server/domain/comment/controller/CommentController.java, src/main/java/com/moa/moa_server/domain/comment/dto/response/CommentDeleteResponse.java, src/main/java/com/moa/moa_server/domain/comment/entity/Comment.java, src/main/java/com/moa/moa_server/domain/comment/handler/CommentErrorCode.java, src/main/java/com/moa/moa_server/domain/comment/service/CommentService.java
- Closes #202
- 댓글 삭제 기능 구현
- DELETE /api/v1/comments/{commentId} API 구현
- 댓글 작성자 본인만 삭제 가능
- 삭제된 댓글은 목록 조회 시 미노출 처리
- 댓글 soft delete 방식 적용 (deletedAt 필드 업데이트)
* 없음
=> feat: 댓글 삭제 API 구현

src/main/java/com/moa/moa_server/domain/comment/repository/CommentRepository.java, src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteDeleteResponse.java, src/main/java/com/moa/moa_server/domain/vote/entity/Vote.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- Closes #204
- 투표 삭제 기능 구현
- 투표 삭제 API (DELETE /api/v1/votes/{voteId}) 구현
- 본인 투표이면서 상태가 REJECTED인 경우에만 삭제 가능
- soft delete 방식
- 연관 데이터: 존재 가능성을 고려하여 처리
- 댓글: 함께 soft delete
- 투표 검열 기록, 투표 응답, 투표 결과: 투표 물리 삭제 시 hard delete 처리
- 삭제된 투표는 목록/상세 조회에서 제외
* 없음
=> feat: 투표 삭제 API 구현

src/main/java/com/moa/moa_server/domain/group/controller/GroupController.java, src/main/java/com/moa/moa_server/domain/group/dto/response/GroupDeleteResponse.java, src/main/java/com/moa/moa_server/domain/group/entity/Group.java, src/main/java/com/moa/moa_server/domain/group/handler/GroupErrorCode.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/group/util/GroupLookupHelper.java, src/main/java/com/moa/moa_server/domain/user/service/UserService.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteRepository.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteRelatedDataCleaner.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- Closes #206
- 그룹 삭제 기능 구현
* `DELETE /api/v1/groups/{groupId}` API 구현
* 그룹 소유자만 삭제 가능하도록 권한 검증 추가
* soft delete 방식
* 삭제된 그룹은 가입 불가, 목록/상세 조회 불가
* 그룹 생성 시 삭제된 그룹의 이름 사용 가능
* 연관 데이터 정리
* 그룹 내 투표 전체 soft delete
* 각 투표의 연관 데이터 정리
* 정리 로직은 `VoteService.deleteVoteByGroupId()`에서 통합 관리
* 없음
=> feat: 그룹 삭제 API 구현

src/main/java/com/moa/moa_server/domain/group/controller/GroupController.java, src/main/java/com/moa/moa_server/domain/group/dto/request/GroupUpdateRequest.java, src/main/java/com/moa/moa_server/domain/group/dto/response/GroupUpdateResponse.java, src/main/java/com/moa/moa_server/domain/group/entity/Group.java, src/main/java/com/moa/moa_server/domain/group/entity/GroupMember.java, src/main/java/com/moa/moa_server/domain/group/service/GroupService.java, src/main/java/com/moa/moa_server/domain/image/service/ImageService.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java, src/test/java/com/moa/moa_server/unit/vote/service/VoteUpdateTest.java
- Closes #212
* 그룹 정보(이름, 소개, 이미지, 초대코드) 수정 기능 구현
* 그룹 소유자 또는 관리자만 수정 가능
* `PATCH /api/v1/groups/{groupId}` API 추가
* 권한 검증: 그룹 멤버면서 `OWNER` 또는 `MANAGER`만 가능
* 그룹 이름/소개 입력값 유효성 검사 및 XSS 필터링 적용
* 그룹 이름 중복 시 `409 Conflict` 반환
* 이미지 URL 변경 시 S3 이미지 처리 로직 적용 (vote/group 구분)
* `changeInviteCode=true` 시 초대코드 새로 생성
* 포스트맨으로 정상 동작 테스트 완료
* 이미지 이동 확인
* 권한 없음 (FORBIDDEN) 테스트 완료
* 없음
=> feat: 그룹 정보 수정 API 구현

src/main/java/com/moa/moa_server/domain/vote/dto/response/VoteDetailResponse.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- Closes #226
- 투표 내용 조회 시 그룹 이름도 함께 전달
- 작업 이유: FE측 화면설계 요구사항
* 없ㅇ ㅁ
=> feat: 투표 내용 조회 시 그룹 이름도 함께 전달

src/main/java/com/moa/moa_server/domain/comment/repository/CommentRepository.java, src/main/java/com/moa/moa_server/domain/comment/service/CommentCountService.java, src/main/java/com/moa/moa_server/domain/group/dto/group_vote/GroupVoteItem.java, src/main/java/com/moa/moa_server/domain/group/service/GroupVoteService.java, src/main/java/com/moa/moa_server/domain/vote/controller/VoteController.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/mine/MyVoteItem.java, src/main/java/com/moa/moa_server/domain/vote/dto/response/submitted/SubmittedVoteItem.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteListService.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- Closes #241
- 투표 목록 조회 응답에 댓글 수 포함
- 참여한 / 내가 만든 / 그룹 투표 목록 조회 시 응답에 댓글 수 필드 추가
- 댓글 수 조회 전용 컴포넌트 `CommentCountService` 추가
- `VoteService`에서 투표 목록 관련 메서드(`getMyVotes()`, `getSubmittedVotes()`)를 `VoteListService`로 분리하여 책임 분산
* 없음
=> fix: 투표 목록 조회 응답에 댓글 수 포함

src/main/java/com/moa/moa_server/domain/vote/scheduler/AIVoteOpenScheduler.java
- Closes #254
- AI 투표 자동 오픈을 위한 스케줄링 주기 변경
- 배경: 오전 10시로 고정되었던 AI 투표 시작 시간이 랜덤 시간으로 변경됨에 따라 스케줄링 변경
- 하루 1회 오전 10시 05분 (KST) → 1시간 단위로 변경
* 없음
* 없음
=> fix: AI 투표 자동 오픈을 1시간 단위 스케줄링으로 변경

.github/workflows/cicd-docker.yml, build.gradle, src/main/java/com/moa/moa_server/domain/vote/scheduler/AIVoteOpenScheduler.java
이번 버전(v3.1.0)에는 AI 투표 상태 변경 스케줄러의 실행 주기가 조정되었습니다.
* `PENDING` 상태의 AI 투표를 시작 시간(`openAt`)에 맞춰 `OPEN`으로 전환하는 스케줄러
* 기존: 매일 오전 10시 5분(KST) 1회 실행 → 변경: 매 1시간마다 정각(KST) 실행
=> release: v3.1.0

src/main/java/com/moa/moa_server/domain/comment/repository/CommentRepository.java, src/main/java/com/moa/moa_server/domain/comment/service/CommentService.java, src/main/java/com/moa/moa_server/domain/ranking/scheduler/RankingScheduler.java, src/main/java/com/moa/moa_server/domain/ranking/service/RankingRedisService.java, src/main/java/com/moa/moa_server/domain/vote/repository/VoteResponseRepository.java, src/main/java/com/moa/moa_server/domain/vote/service/VoteService.java
- Closes #262
- 실시간 그룹 투표 랭킹 생성을 위한 수정된 투표 추적 및 점수 계산 스케줄러 구현
* 댓글 작성 또는 투표 참여 발생 시 해당 투표 ID를 Redis ZSet(`ranking:changed:{yyyyMMdd}`)에 기록
* key는 날짜 기준 UTC, score는 `epochSecond` 기준 UTC 시간 사용
* 매 1시간마다 스케줄러 실행 (`@Scheduled`)
* 최근 1시간 내 수정된 투표 목록 조회
* 댓글 수 + 응답 수를 기반으로 점수 계산
`score = (commentCount + responseCount) / 진행기간(일)`
* 결과를 그룹별 랭킹 ZSet(`ranking:{groupId}:{yyyyMMdd}`)에 저장
* 댓글/응답 수는 현재 매 스케줄 시 DB에서 count 조회하고 있음 → 캐싱 여부는 추후 고려
* 캐시 미스/백업 처리, Top3 조회 API는 다음 PR에서 진행 예정
* 랭킹 갱신 간격은 현재 1시간이나, 트래픽에 따라 조정 가능
=> feat: 랭킹 점수 스케줄러 구현 및 수정된 투표 추적 기능 추가
